[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/src/main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
