import { useLangStore } from '@/store/lang.store';
import { translations } from '@/lib/i18n';

const es = {
  loginTitle: 'GoldTrader — Conexión a cuenta demo',
  loginServer: 'Servidor: Demo-XAUUSD-001 · Latencia: 2ms',
  loginEmail: 'Login (email)',
  loginPassword: 'Contraseña',
  loginSave: 'Guardar contraseña',
  loginConnect: 'Conectar',
  loginConnecting: 'Conectando...',
  loginInvalid: 'Credenciales inválidas',
  loginNewAccount: 'Nueva cuenta',
  loginFooter: 'GoldTrader Simulator v1.0 · XAUUSD · Cuenta demo ilimitada',

  registerTitle: 'GoldTrader — Abrir cuenta demo',
  registerDemoInfo: 'Cuenta demo gratuita',
  registerCapital: 'Capital inicial',
  registerName: 'Nombre',
  registerEmail: 'Email (será tu login)',
  registerPassword: 'Contraseña (mín. 8 caracteres)',
  registerCreate: 'Crear cuenta demo',
  registerCreating: 'Creando cuenta...',
  registerError: 'Error al registrar',
  registerHaveAccount: 'Ya tengo cuenta',
  registerFooter: 'Sin tarjeta de crédito · Sin riesgo · 100% educativo',

  menuFile: 'Archivo',
  menuView: 'Ver',
  menuInsert: 'Insertar',
  menuCharts: 'Gráficos',
  menuTools: 'Herramientas',
  menuWindow: 'Ventana',
  menuHelp: 'Ayuda',
  navChart: 'Gráfico',
  navNewOrder: 'Nueva orden',
  navHistory: 'Historial',
  navMissions: 'Misiones',
  navStats: 'Estadísticas',
  connected: 'Conectado — Servidor Demo',
  disconnected: 'Sin conexión',
  logout: 'Salir',

  marketWatch: 'Market Watch',
  live: 'En vivo',
  offline: 'Sin datos',
  symbol: 'Símbolo',
  bid: 'Compra',
  ask: 'Venta',
  spread: 'Spread',
  onePip: '1 pip',
  oneLot: '1 lote',
  margin: 'Margen',
  realtime: 'Tiempo real',

  navigator: 'Navegador',
  demoAccount: 'Cuenta Demo',
  accountData: 'Datos de cuenta',
  resetAccount: 'Reiniciar cuenta',
  indicators: 'Indicadores',
  missions: 'Misiones',
  activeMissions: 'Misiones activas',
  completedMissions: 'Completadas',
  stats: 'Estadísticas',
  winrate: 'Winrate',
  riskAnalysis: 'Análisis de riesgo',
  fullHistory: 'Historial completo',

  tradePanelTitle: 'Trade',
  historyTab: 'Historial',
  accountTab: 'Cuenta',
  tradeTab: (n: number) => `Trade (${n})`,
  noOpenPositions: 'Sin posiciones abiertas',
  noHistory: 'Sin historial',
  closeBtn: 'Cerrar',
  floatingPL: 'P/L flotante',
  balance: 'Balance',
  equity: 'Equidad',
  plToday: 'P/L Hoy',
  level: 'Nivel',
  xp: 'XP',
  startingBalance: 'Balance inicial',
  openPositions: 'Posiciones abiertas',
  colTime: 'Hora',
  colTicket: 'Ticket',
  colType: 'Tipo',
  colLots: 'Lotes',
  colSymbol: 'Símbolo',
  colEntry: 'Entrada',
  colSL: 'S/L',
  colTP: 'T/P',
  colLivePL: 'P/L Live',
  colOpen: 'Apertura',
  colClose: 'Cierre',
  colExit: 'Salida',
  colRR: 'R/R',
  colPL: 'P/L',
  colRisk: 'Riesgo%',
  colStatus: 'Estado',

  dataSource: (n: number) => `Yahoo Finance · ${n.toLocaleString('es')} velas`,
  refreshData: '⟳ Actualizar datos',
  refreshing: '⟳ Actualizando...',
  startReplay: '▶ Replay',
  stopReplay: '⏹ Detener replay',

  orderTicket: 'Nueva Orden',
  tradeType: 'Tipo',
  lots: 'Volumen (lotes)',
  stopLoss: 'Stop Loss',
  takeProfit: 'Take Profit',
  notes: 'Notas',
  riskCalc: 'Calculadora de riesgo',
  risk: 'Riesgo',
  reward: 'Beneficio',
  rrRatio: 'R/R',
  quickSL: 'SL/TP rápido',
  placeholderNotes: 'Notas opcionales...',
  slRequired: 'SL y TP son obligatorios',
  simulateError: 'Error en simulación',
  buyAt: 'COMPRAR en',
  sellAt: 'VENDER en',

  tpHit: '✅ Take Profit — Operación ganadora',
  slHit: '❌ Stop Loss — Operación perdedora',
  neutral: '⏸ Sin resultado',
  resultUsd: 'Resultado ($)',
  resultPct: 'Resultado (%)',
  exitPrice: 'Precio de salida',
  candlesTraversed: 'Velas recorridas',
  riskPct: 'Riesgo %',
  rrLabel: 'Ratio R/R',
  educationalAnalysis: '📚 Análisis educativo',
  accept: 'Aceptar',

  tradeHistory: 'Historial de operaciones',
  total: 'Total',
  winrateLabel: 'Winrate',
  totalPL: 'P/L Total',
  loading: 'Cargando...',

  traderStats: 'Estadísticas del trader',
  totalTrades: 'Operaciones',
  avgPL: 'P/L Medio',
  avgRisk: 'Riesgo medio',
  avgRR: 'R/R Medio',
  winStreak: 'Racha ganadora',
  lossStreak: 'Racha perdedora',
  winsVsLosses: 'Ganancias vs Pérdidas',
  wins: 'Ganancias',
  losses: 'Pérdidas',
  weeklyPL: 'P/L Semanal',
  behaviourAnalysis: 'Análisis de comportamiento',
  noTradesYet: 'Sin operaciones aún. Ve a Trade para empezar.',
  noStatsYet: 'Sin estadísticas disponibles todavía.',
  noWeeklyData: 'Sin datos semanales todavía.',

  trainingMissions: 'Misiones de entrenamiento',
  evaluateProgress: '🔄 Evaluar progreso',
  active: (n: number) => `Activas (${n})`,
  completed: (n: number) => `Completadas (${n})`,
  noActiveMissions: 'No hay misiones activas pendientes.',
  keyConceptsTitle: '📚 Conceptos clave del trading de oro',
  concepts: [
    { title: 'Gestión del riesgo', body: 'Nunca arriesgues más del 1-2% de tu capital por operación. Con $10,000, tu pérdida máxima por trade debe ser $100–$200.' },
    { title: 'Ratio R/R', body: 'Siempre busca un ratio riesgo/beneficio de al menos 2:1. Por cada $1 que arriesgas, debes poder ganar $2.' },
    { title: 'Stop Loss', body: 'Es tu seguro. Colócalo en un nivel técnico relevante (soporte/resistencia), no en un precio arbitrario.' },
    { title: 'Oro (XAUUSD)', body: 'El oro se mueve con la inflación, el dólar y el riesgo global. 1 lote = 100 oz. Valor del pip ≈ $10 por pip.' },
  ],

  appLoading: 'GoldTrader MT · Cargando...',

  // ── Menu items ──
  newDemoAccount: 'Nueva cuenta demo',
  confirmReset: '¿Reiniciar cuenta? Perderás todo el historial.',
  exportHistoryCsv: 'Exportar historial (CSV)',
  menuItemChart: 'Gráfico',
  menuItemSimulator: 'Simulador',
  menuItemHistory: 'Historial',
  menuItemMissions: 'Misiones',
  menuItemAcademy: 'Academia',
  menuItemStats: 'Estadísticas',
  menuItemVolume: 'Volumen',
  menuItemNewOrder: 'Nueva orden',
  menuItemHLine: 'Línea horizontal',
  menuItemTLine: 'Línea de tendencia',
  menuItemFib: 'Fibonacci',
  menuItemMA20: 'MA 20',
  menuItemMA50: 'MA 50',
  menuItemBB: 'Bandas de Bollinger',
  menuItemReplayStart: '▶ Iniciar Replay',
  menuItemReplayStop: '⏹ Detener Replay',
  menuItemRiskCalc: 'Calculadora de lotes',
  menuItemLangEs: '🇪🇸 Español',
  menuItemLangEn: '🇬🇧 English',
  menuItemLangNl: '🇳🇱 Nederlands',
  menuItemEvaluate: 'Evaluar misiones',
  menuItemRelaunch: 'Nueva cuenta demo',
  menuItemFullscreen: 'Pantalla completa',
  menuItemNavPanel: 'Panel navegador',

  // ── FTMO tab ──
  ftmoTabLabel: (s: string) => `FTMO: ${s}`,
  ftmoDailyLoss: 'Pérdida diaria',
  ftmoTotalDrawdown: 'Drawdown total',
  ftmoProfitTarget: 'Objetivo de beneficio',
  ftmoStatusOk: '✅ Dentro de los límites',
  ftmoStatusWarning: '⚠ Zona de riesgo',
  ftmoStatusDanger: '🚨 Límite superado',
  ftmoExplainer: 'Simulación de cuenta fondeada FTMO',
  ftmoCurrentBalance: 'Balance actual',
  ftmoPLToday: 'P/L hoy',
  ftmoTradesToday: 'Trades hoy',
  ftmoWinRateToday: 'Winrate hoy',
  ftmoAvgRRToday: 'R/R medio hoy',
  ftmoRulesTitle: '📋 Reglas FTMO simuladas',
  ftmoDailyRule: 'Pérdida diaria máx: -5% del balance inicial',
  ftmoDrawdownRule: 'Drawdown máx: -10% del balance inicial',
  ftmoTargetRule: 'Objetivo de beneficio: +8% del balance inicial',
  ftmoInsideLimits: 'Dentro del límite',
  ftmoLimitExceeded: 'Límite superado',
  ftmoDailyBlockedMsg: '🚨 Límite diario superado. Pausa trading hoy.',
  ftmoReadyTitle: '🏆 ¡Listo para fondeo!',
  ftmoReadyText: 'Has alcanzado el 8% de beneficio. Intenta una cuenta real FTMO.',

  // ── Account tooltips ──
  tipBalance: 'Capital en efectivo disponible, excluyendo posiciones abiertas.',
  tipEquity: 'Balance + P/L flotante de posiciones abiertas actuales.',
  tipFloatingPL: 'Ganancia/pérdida no realizada de posiciones abiertas.',
  tipPLToday: 'Suma de todas las operaciones cerradas hoy.',
  tipLevel: 'Tu nivel de trader según XP acumulada.',
  tipXP: 'Puntos de experiencia. Ganas XP completando misiones y trades.',
  tipStartingBalance: 'Capital inicial con el que abriste esta cuenta demo.',
  tipOpenPositions: 'Número de posiciones actualmente abiertas.',

  // ── SimulationResult tabs ──
  tabAnalysis: 'Análisis',
  tabFunding: 'Fondeo',
  tabJournal: 'Diario',
  tradeGradePerfect: '⭐ Perfecto',
  tradeGradeGood: '✅ Bueno',
  tradeGradeOk: '📈 Aceptable',
  tradeGradePoor: '⚠ Mejorable',
  criteriaMet: (n: number) => `${n}/4 criterios cumplidos`,
  tradeEvalTitle: 'Evaluación del trade',
  simulatorAnalysisLabel: 'Análisis del simulador',
  whatNowTitle: '¿Qué hago ahora?',
  nextTradeBtn: 'Próximo trade',
  evaluateMissionsLink: 'Ver misiones',
  ftmoFundingNote: 'Este trade sería válido en una cuenta fondeada.',
  ftmoReadyNote: '🏆 ¡Listo para fondeo real!',
  ftmoReadyBody: 'Tus métricas de hoy cumplen los requisitos FTMO. Sigue manteniendo la consistencia.',
  journalSectionTitle: '📓 Diario de trading',
  journalTipText: 'Llevar un diario es un hábito clave de los traders profesionales.',
  journalAcademyLink: 'Ver módulo de diario →',
  journalField1: '¿Por qué entraste en este trade?',
  journalField2: '¿Qué salió bien?',
  journalField3: '¿Qué mejorarías?',
  journalField4: '¿Cuánto riesgo tomaste y fue correcto?',
  journalPlaceholder1: 'Ej: Señal de ruptura en soporte con volumen...',
  journalPlaceholder2: 'Ej: El SL estaba bien colocado...',
  journalPlaceholder3: 'Ej: Entré tarde, podría haber esperado...',
  journalPlaceholder4: 'Ej: Arriesgué 1%, fue adecuado...',
  academyLevelLink: 'Ver lección relacionada →',

  // ── Trade criteria ──
  criteriaRiskOk: (pct: string) => `✅ Riesgo controlado (${pct}%)`,
  criteriaRiskBad: (pct: string) => `⚠ Riesgo elevado (${pct}%)`,
  criteriaRiskTip: 'Riesgo ideal: ≤2% del balance por trade.',
  criteriaRROk: (rr: string) => `✅ R/R profesional (${rr}:1)`,
  criteriaRRBad: (rr: string) => `⚠ R/R bajo (${rr}:1 — busca ≥2)`,
  criteriaRRTip: 'Con R/R ≥2:1 solo necesitas un 34% de winrate para ser rentable.',
  criteriaWin: '✅ Trade ganador',
  criteriaSLHit: '❌ Stop Loss activado',
  criteriaNeutral: '⏸ Sin resultado claro',
  criteriaWinTip: 'Ganar no es lo más importante: el proceso lo es.',
  criteriaSLTip: 'Un SL activado bien colocado es una buena operación. El riesgo estaba controlado.',
  criteriaSLSet: '✅ Stop Loss colocado',
  criteriaSLMissing: '⚠ Sin Stop Loss — riesgo sin control',
  criteriaSLSetTip: 'El SL protege tu cuenta. Sin él, una operación puede borrar semanas de ganancias.',

  // ── Win/loss advice ──
  winAdvice1: 'Repite el proceso: analiza por qué funcionó y busca setups similares.',
  winAdvice2: 'No subas el tamaño de posición por entusiasmo. Mantén el 1-2% de riesgo.',
  winAdvice3: 'Anota en tu diario: ¿qué señales viste? ¿el R/R fue suficiente?',
  lossAdvice1: 'Si el SL estaba en un nivel técnico válido, es una buena operación aunque perdiste.',
  lossAdvice2: 'Revisa: ¿entré en el momento correcto? ¿el riesgo era adecuado?',
  lossAdvice3: 'No recuperes pérdidas con el siguiente trade. Mantén el tamaño de posición.',

  // ── Lot Calculator ──
  lotCalcTitle: 'Calculadora de lotes — XAUUSD',
  lotCalcBalanceLabel: 'Balance ($)',
  lotCalcEntryLabel: 'Precio de entrada',
  lotCalcLiveNote: '(en vivo)',
  lotCalcRiskLabel: 'Riesgo por trade',
  lotCalcRiskMoney: 'Riesgo en USD:',
  lotCalcSLLabel: 'Stop Loss (pips)',
  lotCalcRRLabel: 'Ratio R/R',
  lotCalcRRWarning: '⚠ R/R inferior a 2:1 — no recomendado para traders profesionales',
  lotCalcResultTitle: '📊 Resultado calculado',
  lotCalcLotsLabel: 'Lotes',
  lotCalcSLCostLabel: 'Pérdida SL',
  lotCalcTPGainLabel: 'Ganancia TP',
  lotCalcEntryLabel2: 'Entrada',
  lotCalcPipTableTitle: (sl: number, tp: number) => `Tabla de pips — SL: ${sl}p / TP: ${tp}p`,
  lotCalcColLot: 'Lote',
  lotCalcColPerPip: '$/pip',
  lotCalcColSL: 'SL ($)',
  lotCalcColTP: 'TP ($)',
  lotCalcWhyTitle: '💡 ¿Por qué calcular el tamaño de posición?',
  lotCalcWhyText: (pct: number) => `Con ${pct}% de riesgo, si el mercado te da la razón ganas el doble (o más), y si se activa el SL solo pierdes ${pct}% de tu balance. Esta es la base de la gestión profesional del capital.`,
  lotCalcCloseBtn: 'Cerrar calculadora',

  // ── Trader Score ──
  traderScoreTitle: 'Puntuación de trader',
  traderGradeElite: 'Élite',
  traderGradeAdvanced: 'Avanzado',
  traderGradeIntermediate: 'Intermedio',
  traderGradeBeginner: 'Principiante',
  traderGradeCritical: 'Crítico',
  traderVerdictElite: 'Trading de nivel profesional. Listo para fondeo real.',
  traderVerdictAdvanced: 'Muy buenas métricas. Sigue así y considera una cuenta fondeada.',
  traderVerdictIntermediate: 'Progreso sólido. Trabaja en las áreas señaladas.',
  traderVerdictBeginner: 'Base correcta. Necesitas más práctica y consistencia.',
  traderVerdictCritical: 'Revisar gestión de riesgo urgentemente antes de continuar.',
  traderImprovementsTitle: 'Puntos de mejora prioritarios',
  traderNoIssues: '✅ Sin puntos críticos de mejora. Mantén la consistencia y considera intentar una cuenta de fondeo real.',
  traderAdviceWinRateLow: 'Winrate bajo (40-50%): revisa tus entradas y espera señales más claras.',
  traderAdviceWinRateCritical: 'Winrate crítico (<40%): replantea tu estrategia de entrada.',
  traderAdviceRRLow: 'R/R medio bajo (1.5-2): intenta mejorar el ratio con TPs más amplios.',
  traderAdviceRRCritical: 'R/R medio insuficiente (<1.5): estás perdiendo ventaja estadística.',
  traderAdviceRiskHigh: 'Riesgo promedio alto (2-3%): reduce el tamaño de posición.',
  traderAdviceRiskCritical: 'Riesgo excesivo (>3%): esto viola las reglas FTMO y de gestión profesional.',
  traderAdviceDrawdownHigh: 'Drawdown elevado (10-20%): controla el riesgo diario.',
  traderAdviceDrawdownCritical: 'Drawdown crítico (>20%): necesitas pausar y revisar tu estrategia.',
  traderAdviceTradesLow: 'Pocas operaciones (10-20): necesitas más muestras para estadísticas fiables.',
  traderAdviceTradesCritical: 'Muy pocas operaciones (<10): las estadísticas no son representativas aún.',

  // ── Stats tooltips ──
  tipWinRate: 'Porcentaje de trades ganadores. Con R:R 2:1 solo necesitas el 34% para ser rentable.',
  tipTotalPL: 'Suma total de todos los resultados en USD.',
  tipTotalTrades: 'Total de operaciones cerradas. Necesitas 20-30 para estadísticas fiables.',
  tipAvgPL: 'Resultado medio por trade. Un valor positivo sostenido indica sistema rentable.',
  tipAvgRisk: 'Riesgo promedio por trade. La gestión profesional exige ≤2% por trade.',
  tipAvgRR: 'Ratio riesgo:recompensa medio. El estándar mínimo profesional es 2:1.',
  tipWinStreak: 'Mayor racha de trades ganadores consecutivos.',
  tipLossStreak: 'Mayor racha de pérdidas consecutivas. Con R/R 2:1 puedes sobrevivir rachas largas.',
  tipMaxDrawdown: 'Caída máxima desde el pico de equity. FTMO permite hasta -10%.',
  equityCurveLabel: 'Curva de Equity',

  // ── Onboarding wizard ──
  tourHeader: 'GoldTrader MT — Guía de inicio',
  tourSkip: 'Saltar tour',
  tourBack: '← Atrás',
  tourStepOf: (cur: number, total: number) => `${cur} de ${total}`,
  tourNext: 'Siguiente →',
  tourFinish: '¡Ir al simulador! ⚡',

  tourLangTitle: 'Selecciona tu idioma',
  tourLangSub: 'Select your language · Kies je taal',
  tourLangContinue: 'Continuar →',

  tourWelcomeTitle: 'Bienvenido a GoldTrader MT',
  tourWelcomeSub: 'El simulador que te prepara para pasar cuentas de fondeo',
  tourWelcomeCta: 'Empezar el tour →',
  tourWelcomeBody: 'Este no es un juego. Es un simulador profesional diseñado para que aprendas a operar XAU/USD (oro) exactamente como lo harías en una cuenta de fondeo real (FTMO, MyFundedFX…). Cada decisión que tomes aquí — el tamaño del lote, el Stop Loss, el ratio R:R — importa. El simulador registra todo y te dice si vas por el camino correcto.',
  tourWelcomeF1Label: 'Aprende la teoría',
  tourWelcomeF1Sub: 'Academia XAU paso a paso',
  tourWelcomeF2Label: 'Practica en vivo',
  tourWelcomeF2Sub: 'Precio real del oro',
  tourWelcomeF3Label: 'Pasa el fondeo',
  tourWelcomeF3Sub: 'Reglas FTMO integradas',

  tourGoldTitle: '¿Qué es el XAU/USD?',
  tourGoldSub: 'El activo más importante que vas a operar',
  tourGoldCta: 'Siguiente →',
  tourGoldB1: 'El oro mueve $10–$30 al día. Con un lote correcto, eso son $100–$300 de ganancia o pérdida.',
  tourGoldB2: 'Opera 24 horas, de lunes a viernes. Los momentos más volátiles: apertura de Londres (9:00) y Nueva York (14:00).',
  tourGoldB3: 'Es un activo de refugio seguro: sube en crisis y cae cuando la economía va bien.',
  tourGoldTip: '💡 Mira arriba a la derecha del toolbar:',
  tourGoldTipSub: ' el precio en vivo del oro se actualiza en tiempo real.',

  tourLotsTitle: 'Lotes, riesgo y Stop Loss',
  tourLotsSub: 'Los 3 conceptos que salvan cuentas',
  tourLotsCta: 'Siguiente →',
  tourLotsMicro: 'Micro',
  tourLotsMini: 'Mini',
  tourLotsStd: 'Estándar',
  tourLotsSL: 'Stop Loss (SL): el precio donde tu trade cierra automáticamente para limitar la pérdida. Nunca abras un trade sin él.',
  tourLotsTP: 'Take Profit (TP): el precio donde tu trade cierra con ganancia. Ponlo siempre al doble del SL (R:R 1:2).',
  tourLotsRule: 'Regla de oro: nunca arriesgues más del 1–2% de tu cuenta por trade. Con $10.000 = máximo $100–$200 por operación.',

  tourIfaceTitle: 'Tu plataforma en 30 segundos',
  tourIfaceSub: 'Todo lo que necesitas saber para empezar',
  tourIfaceCta: 'Siguiente →',
  tourIfaceZ1Label: 'Barra superior (Archivo, Ver…)',
  tourIfaceZ1Desc: 'Menús con todas las acciones: cambiar timeframe, activar indicadores, calculadora de riesgo.',
  tourIfaceZ2Label: 'Panel izquierdo — Market Watch',
  tourIfaceZ2Desc: 'Precio del oro en tiempo real. El precio verde = subiendo. Rojo = bajando.',
  tourIfaceZ3Label: 'Panel izquierdo — Navigator',
  tourIfaceZ3Desc: 'Acceso rápido a indicadores (actívalos con un clic), cuenta y misiones.',
  tourIfaceZ4Label: 'Gráfico central',
  tourIfaceZ4Desc: 'El precio del oro en velas japonesas. Cada vela = 1 período (M5, H1…). Aquí analizas.',
  tourIfaceZ5Label: 'Panel inferior — Terminal',
  tourIfaceZ5Desc: 'Tus trades abiertos, historial y datos de tu cuenta (balance, XP, nivel).',
  tourIfaceZ6Label: 'Barra ⚡ Nueva orden',
  tourIfaceZ6Desc: 'El botón más importante. Aquí abres y cierras tus operaciones.',

  tourFirstTitle: '¡Listo para tu primer trade!',
  tourFirstSub: 'Sigue estos 5 pasos exactos',
  tourFirstCta: '¡Ir al simulador! ⚡',
  tourFirstS1: 'Observa el gráfico durante 30 segundos. ¿El precio tiende a subir o bajar?',
  tourFirstS2: 'Haz clic en ⚡ "Nueva orden" en el toolbar superior.',
  tourFirstS3: 'Selecciona el lote: usa 0.01 (micro) para tu primer trade.',
  tourFirstS4: 'Pon Stop Loss a 30 pips y Take Profit a 60 pips (R:R 1:2).',
  tourFirstS5: 'Si crees que sube → BUY (verde). Si baja → SELL (rojo). ¡Confirma!',
  tourFirstNote1: '✅ Recuerda: no importa si ganas o pierdes en el primero. Lo que importa es que usaste SL y R:R 1:2.',
  tourFirstNote2: '🎯 Después de cerrar el trade, ve a "Misiones" y pulsa "Evaluar progreso" para ganar tu primer XP.',

  // ── OrderTicket ──
  otNoSl: 'Sin SL = sin riesgo calculado',
  otGreat: (pct: number) => `${pct.toFixed(2)}% — Gestión perfecta`,
  otOk: (pct: number) => `${pct.toFixed(2)}% — Dentro del límite`,
  otWarn: (pct: number) => `${pct.toFixed(2)}% — Límite FTMO: 2%`,
  otDanger: (pct: number) => `${pct.toFixed(2)}% — ¡Demasiado riesgo!`,
  otSlLabel: 'Stop Loss configurado',
  otTpLabel: 'Take Profit configurado',
  otRiskLabel: 'Riesgo ≤ 2%',
  otQuality: 'Calidad del setup',
  otIdeal: 'Setup ideal',
  otGood: 'Buen setup',
  otBasic: 'Setup básico',
  otIncomplete: 'Setup incompleto',
  otSlPlaceholder: 'Precio de stop loss',
  otTpPlaceholder: 'Precio de take profit',
  otNoSlToggle: 'Sin SL = sin riesgo calculado',
  otHelp: 'ayuda',
  otHide: 'ocultar',
  otBalanceLabel: 'Balance',
  otRiskUsd: 'Riesgo ($)',
  otRiskPct: 'Riesgo (%)',
  otReward: 'Beneficio pot.',
  otRiskIdeal: 'Riesgo ideal:',
  otSlTooltip: 'El Stop Loss cierra tu trade automáticamente si el mercado va en tu contra. Sin SL, una pérdida puede destruir tu cuenta mientras duermes.',

  // ── Trial / Payment ──
  trialExpiredTitle: 'Tu período de prueba ha finalizado',
  trialExpiredBody: 'Para seguir usando GoldTrader MT, activa tu acceso completo por un único pago de €9,95.',
  trialPayBtn: 'Activar acceso — €9,95',
  trialDaysLeft: (n: number) => `Prueba gratuita · ${n} día${n !== 1 ? 's' : ''} restante${n !== 1 ? 's' : ''}`,
  trialUpgradeBtn: 'Activar — €9,95',
} as const;

export type T = typeof es;

const dict: Record<string, typeof es> = {
  es,
  en: translations.en as unknown as typeof es,
  nl: translations.nl as unknown as typeof es,
};

export function useT(): typeof es {
  const lang = useLangStore((s) => s.lang);
  return dict[lang] ?? es;
}
