import { useLangStore } from '@/store/lang.store';
import { translations } from '@/lib/i18n';

const es = {
  loginTitle: 'GoldTrader — Conexión a cuenta demo',
  loginServer: 'Servidor: Demo-XAUUSD-001 · Latencia: 2ms',
  loginEmail: 'Login (email)',
  loginPassword: 'Contraseña',
  loginSave: 'Guardar contraseña',
  loginConnect: 'Conectar',
  loginConnecting: 'Conectando...',
  loginInvalid: 'Credenciales inválidas',
  loginNewAccount: 'Nueva cuenta',
  loginFooter: 'GoldTrader Simulator v1.0 · XAUUSD · Cuenta demo ilimitada',

  registerTitle: 'GoldTrader — Abrir cuenta demo',
  registerDemoInfo: 'Cuenta demo gratuita',
  registerCapital: 'Capital inicial',
  registerName: 'Nombre',
  registerEmail: 'Email (será tu login)',
  registerPassword: 'Contraseña (mín. 8 caracteres)',
  registerCreate: 'Crear cuenta demo',
  registerCreating: 'Creando cuenta...',
  registerError: 'Error al registrar',
  registerHaveAccount: 'Ya tengo cuenta',
  registerFooter: 'Sin tarjeta de crédito · Sin riesgo · 100% educativo',

  menuFile: 'Archivo',
  menuView: 'Ver',
  menuInsert: 'Insertar',
  menuCharts: 'Gráficos',
  menuTools: 'Herramientas',
  menuWindow: 'Ventana',
  menuHelp: 'Ayuda',
  navChart: 'Gráfico',
  navNewOrder: 'Nueva orden',
  navHistory: 'Historial',
  navMissions: 'Misiones',
  navStats: 'Estadísticas',
  connected: 'Conectado — Servidor Demo',
  disconnected: 'Sin conexión',
  logout: 'Salir',

  marketWatch: 'Market Watch',
  live: 'En vivo',
  offline: 'Sin datos',
  symbol: 'Símbolo',
  bid: 'Compra',
  ask: 'Venta',
  spread: 'Spread',
  onePip: '1 pip',
  oneLot: '1 lote',
  margin: 'Margen',
  realtime: 'Tiempo real',

  navigator: 'Navegador',
  demoAccount: 'Cuenta Demo',
  accountData: 'Datos de cuenta',
  resetAccount: 'Reiniciar cuenta',
  indicators: 'Indicadores',
  missions: 'Misiones',
  activeMissions: 'Misiones activas',
  completedMissions: 'Completadas',
  stats: 'Estadísticas',
  winrate: 'Winrate',
  riskAnalysis: 'Análisis de riesgo',
  fullHistory: 'Historial completo',

  tradePanelTitle: 'Trade',
  historyTab: 'Historial',
  accountTab: 'Cuenta',
  tradeTab: (n: number) => `Trade (${n})`,
  noOpenPositions: 'Sin posiciones abiertas',
  noHistory: 'Sin historial',
  closeBtn: 'Cerrar',
  floatingPL: 'P/L flotante',
  balance: 'Balance',
  equity: 'Equidad',
  plToday: 'P/L Hoy',
  level: 'Nivel',
  xp: 'XP',
  startingBalance: 'Balance inicial',
  openPositions: 'Posiciones abiertas',
  colTime: 'Hora',
  colTicket: 'Ticket',
  colType: 'Tipo',
  colLots: 'Lotes',
  colSymbol: 'Símbolo',
  colEntry: 'Entrada',
  colSL: 'S/L',
  colTP: 'T/P',
  colLivePL: 'P/L Live',
  colOpen: 'Apertura',
  colClose: 'Cierre',
  colExit: 'Salida',
  colRR: 'R/R',
  colPL: 'P/L',
  colRisk: 'Riesgo%',
  colStatus: 'Estado',

  dataSource: (n: number) => `Yahoo Finance · ${n.toLocaleString('es')} velas`,
  refreshData: '⟳ Actualizar datos',
  refreshing: '⟳ Actualizando...',
  startReplay: '▶ Replay',
  stopReplay: '⏹ Detener replay',

  orderTicket: 'Nueva Orden',
  tradeType: 'Tipo',
  lots: 'Volumen (lotes)',
  stopLoss: 'Stop Loss',
  takeProfit: 'Take Profit',
  notes: 'Notas',
  riskCalc: 'Calculadora de riesgo',
  risk: 'Riesgo',
  reward: 'Beneficio',
  rrRatio: 'R/R',
  quickSL: 'SL/TP rápido',
  placeholderNotes: 'Notas opcionales...',
  slRequired: 'SL y TP son obligatorios',
  simulateError: 'Error en simulación',
  buyAt: 'COMPRAR en',
  sellAt: 'VENDER en',

  tpHit: '✅ Take Profit — Operación ganadora',
  slHit: '❌ Stop Loss — Operación perdedora',
  neutral: '⏸ Sin resultado',
  resultUsd: 'Resultado ($)',
  resultPct: 'Resultado (%)',
  exitPrice: 'Precio de salida',
  candlesTraversed: 'Velas recorridas',
  riskPct: 'Riesgo %',
  rrLabel: 'Ratio R/R',
  educationalAnalysis: '📚 Análisis educativo',
  accept: 'Aceptar',

  tradeHistory: 'Historial de operaciones',
  total: 'Total',
  winrateLabel: 'Winrate',
  totalPL: 'P/L Total',
  loading: 'Cargando...',

  traderStats: 'Estadísticas del trader',
  totalTrades: 'Operaciones',
  avgPL: 'P/L Medio',
  avgRisk: 'Riesgo medio',
  avgRR: 'R/R Medio',
  winStreak: 'Racha ganadora',
  lossStreak: 'Racha perdedora',
  winsVsLosses: 'Ganancias vs Pérdidas',
  wins: 'Ganancias',
  losses: 'Pérdidas',
  weeklyPL: 'P/L Semanal',
  behaviourAnalysis: 'Análisis de comportamiento',
  noTradesYet: 'Sin operaciones aún. Ve a Trade para empezar.',
  noStatsYet: 'Sin estadísticas disponibles todavía.',
  noWeeklyData: 'Sin datos semanales todavía.',

  trainingMissions: 'Misiones de entrenamiento',
  evaluateProgress: '🔄 Evaluar progreso',
  active: (n: number) => `Activas (${n})`,
  completed: (n: number) => `Completadas (${n})`,
  noActiveMissions: 'No hay misiones activas pendientes.',
  keyConceptsTitle: '📚 Conceptos clave del trading de oro',
  concepts: [
    { title: 'Gestión del riesgo', body: 'Nunca arriesgues más del 1-2% de tu capital por operación. Con $10,000, tu pérdida máxima por trade debe ser $100–$200.' },
    { title: 'Ratio R/R', body: 'Siempre busca un ratio riesgo/beneficio de al menos 2:1. Por cada $1 que arriesgas, debes poder ganar $2.' },
    { title: 'Stop Loss', body: 'Es tu seguro. Colócalo en un nivel técnico relevante (soporte/resistencia), no en un precio arbitrario.' },
    { title: 'Oro (XAUUSD)', body: 'El oro se mueve con la inflación, el dólar y el riesgo global. 1 lote = 100 oz. Valor del pip ≈ $10 por pip.' },
  ],

  appLoading: 'GoldTrader MT · Cargando...',
} as const;

export type T = typeof es;

const dict: Record<string, typeof es> = {
  es,
  en: translations.en as unknown as typeof es,
  nl: translations.nl as unknown as typeof es,
};

export function useT(): typeof es {
  const lang = useLangStore((s) => s.lang);
  return dict[lang] ?? es;
}
